spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://34.69.229.31:3306/mango
    username: root
    password: J&2Q[vZ6C4,R)0Ja
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          format_sql: true
          show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    descriptor:
      sql: DEBUG

